### ISSUE TITLE
Unable to Login with Discord

### ISSUE THREAD

**Issue by WilliamCVan** [mellowagain/pomu#23]
Hello,

I wanted to submit an url to be added to the queue which requires me to sign in. I tried to login via Discord (twitter and youtube greyed out). After I click the 'Authorize' button, the redirect URL is returning a 502 response, not allowing me to login.

Redirected URL (sanitized): https://dev.pomu.app/oauth/discord/redirect?code=4dps0SrWepRqbXXXXXX&state=2277768XXXXX

![image](https://user-images.githubusercontent.com/6517885/230157785-8c027aaf-2aca-40ad-b5f2-c5dfb20481cc.png)

Thank you

**Comment by mellowagain** [comment]
hi, thanks for the report! i've traced back the issue to the discord api returning `null` for your users' `avatar` field, which we didn't expect. we now handle this correctly.

i will deploy the new version to https://dev.pomu.app in just a bit. let me know if it works then or if you still run into issues.

edit: i just deployed the new version

**Comment by WilliamCVan** [comment]
@mellowagain Thank you for your help and quick fix! Verified login is working
